version: "3.8"

services:
  bff-auth-gateway:
    ports:
      - "4031:4031"
    container_name: bff-auth-gateway
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/amd64
    image: beartrack/bff-auth-gateway:${IMAGE}
    environment:
      PORT: "4031"
      THROTTLE_TTL: "60000"
      THROTTLE_LIMIT: "200"
      HTTPCLIENT_ATTEMPTS: 4
      JWT_SECRET: $JWT_SECRET
      JWT_SECRET_EXPIRES_IN: "1 days"
      JWT_SECRET_EXPIRES_REFRESH_IN: "15 days"
      JWT_SECRET_ATTEMPTS_REFRESH_IN: 1
      MONGODB_URL: $MONGODB_URL
      MONGODB_USER: $MONGODB_USER
      URL_V1: "http://192.169.5.5:4013/api/v1"
      URL_V2: "http://192.169.5.11:4019/api/v2"
      URL_GATEWAY: "http://192.169.5.13:4021/api/v1"
      URL_MS_USERS: "http://192.169.5.18:4033/api/v1"
    networks:
      OTS_NETWORK:
        ipv4_address: 192.169.5.17

networks:
  OTS_NETWORK:
    external: true
