name: CI/CD Pipeline

on:
  push:
    branches:
      - qa
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout CODE 🛬'
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image for QA
        if: github.ref == 'refs/heads/qa'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: facilparking/bff-auth-gateway:qa

      - name: Build and push Docker image for Production
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: facilparking/bff-auth-gateway:latest

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/qa'

    steps:
      - name: Deploy to QA server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST_QA }}
          username: ${{ secrets.SERVER_USERNAME_QA }}
          password: ${{ secrets.SERVER_PASSWORD_QA }}
          port: 22
          script: |
            docker pull facilparking/bff-auth-gateway:qa
            cd /opt/setup-facilparking/bff-auth-gateway
            docker-compose --env-file prod.env down
            docker-compose --env-file prod.env up -d

  deploy-main:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to PROD server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST_PROD }}
          username: ${{ secrets.SERVER_USERNAME_PROD }}
          password: ${{ secrets.SERVER_PASSWORD_PROD }}
          port: 22
          script: |
            docker pull facilparking/bff-auth-gateway:latest
            cd /opt/setup-facilparking/bff-auth-gateway
            docker-compose --env-file prod.env down
            docker-compose --env-file prod.env up -d